services:
  db:
    image: mysql:8.0
    container_name: gachimura-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gachimura
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gachimura-backend
    ports:
      - "8000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run start:dev
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_NAME: gachimura
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gachimura-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev
    environment:
      - NEXT_PUBLIC_DOCKER=true

volumes:
  db_data:
